// Client-side Feature enum — mirrors the Convex schema Feature union
export enum Feature {
  // Core
  STUDENTS = 'STUDENTS',
  STAFF = 'STAFF',
  ATTENDANCE = 'ATTENDANCE',
  FEES = 'FEES',
  ZRA_INVOICING = 'ZRA_INVOICING',
  GUARDIAN_PORTAL = 'GUARDIAN_PORTAL',
  SMS_NOTIFICATIONS = 'SMS_NOTIFICATIONS',
  SCHOOL_CUSTOMISATION = 'SCHOOL_CUSTOMISATION',

  // Academic variants
  ECZ_EXAMS = 'ECZ_EXAMS',
  SEMESTER_SYSTEM = 'SEMESTER_SYSTEM',
  GPA = 'GPA',
  HEA_COMPLIANCE = 'HEA_COMPLIANCE',
  LMS = 'LMS',
  PORTFOLIO = 'PORTFOLIO',
  TIMETABLE = 'TIMETABLE',

  // Residential
  BOARDING = 'BOARDING',
  POCKET_MONEY = 'POCKET_MONEY',
  SICK_BAY = 'SICK_BAY',
  VISITOR_LOG = 'VISITOR_LOG',
  MEAL_PLANS = 'MEAL_PLANS',

  // Transport
  TRANSPORT = 'TRANSPORT',
  GPS_TRACKING = 'GPS_TRACKING',

  // Library
  LIBRARY = 'LIBRARY',
  ELIBRARY = 'ELIBRARY',

  // Optional add-ons
  SPORTS = 'SPORTS',
  CANTEEN = 'CANTEEN',
  ASSET_MANAGEMENT = 'ASSET_MANAGEMENT',
  AI_INSIGHTS = 'AI_INSIGHTS',
  PTM_SCHEDULER = 'PTM_SCHEDULER',
  PERIOD_ATTENDANCE = 'PERIOD_ATTENDANCE',
  WHATSAPP_NOTIFICATIONS = 'WHATSAPP_NOTIFICATIONS',
}
